import react from 'react'

function Banner() {
    return (
<>
<div className="bg-slate-900">
      
      <div className="bg-gradient-to-b from-violet-600/[.15] via-transparent">
        
        <div className="max-w-[85rem] mx-auto px-4 sm:px-6 lg:px-8 py-24 space-y-8">
          
          
          <div className="flex justify-center">
            
            <a className="group inline-block bg-white/[.05] hover:bg-white/[.1] border border-white/[.05] p-1 pl-4 rounded-full shadow-md" href="../figma.html">
              
              <p className="mr-2 inline-block text-white text-sm">
              Insight-Eye: A Smart System for Real-Time Eyesight Assessment using Computer Vision and NLP
              </p>
              
              <span className="group-hover:bg-white/[.1] py-2 px-3 inline-flex justify-center items-center gap-x-2 rounded-full bg-white/[.075] font-semibold text-white text-sm">
                
                <svg className="w-2.5 h-2.5" width="16" height="16" viewBox="0 0 16 16" fill="none">
                  
                  <path d="M5.27921 2L10.9257 7.64645C11.1209 7.84171 11.1209 8.15829 10.9257 8.35355L5.27921 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"></path>
                  
                </svg>
                
              </span>
              
            </a>
            
          </div>
          
          
          
          <div className="max-w-3xl text-center mx-auto">
            
            <h1 className="block font-medium text-gray-200 text-4xl sm:text-5xl md:text-6xl lg:text-7xl">
            Real-Time Eyesight Assessment
            </h1>
            
          </div>
          
          
          <div className="max-w-3xl text-center mx-auto">
            
            <p className="text-lg text-gray-400">
            InsightEye is a real-time eyesight testing system that combines computer vision and natural language processing (NLP) technologies. It captures and analyzes visual behaviors such as eye movements and fixation points to provide an accurate and objective measurement of an individual&apos;s eyesight health. The system can detect and classify different visual patterns in real-time and provide immediate feedback to the user or healthcare professionals. The NLP component further analyzes the data generated by the computer vision algorithms to offer insights into the individual&apos;s eyesight health status. This paper presents a novel approach to combining computer vision and NLP technologies for real-time eyesight testing.
            </p>
            
          </div>
          
          
          <div className="text-center">
            
            <a className="inline-flex justify-center items-center gap-x-3 text-center bg-gradient-to-tl from-blue-600 to-violet-600 shadow-lg shadow-transparent hover:shadow-blue-700/50 border border-transparent text-white text-sm font-medium rounded-full focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white py-3 px-6 dark:focus:ring-offset-gray-800" href="#">
              Get started
              <svg className="w-2.5 h-2.5" width="16" height="16" viewBox="0 0 16 16" fill="none">
                
                <path d="M5.27921 2L10.9257 7.64645C11.1209 7.84171 11.1209 8.15829 10.9257 8.35355L5.27921 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"></path>
                
              </svg>
              
            </a>
            
          </div>
          
          
        </div>
        
      </div>
      
    </div>
    
</>
    )
    }
export default Banner